from .ddaig import DDAIG
from .daeldg import DAELDG
from .vanilla import Vanilla
from .crossgrad import CrossGrad
from .cxrvanilla import CxrVanilla
from .cxrdael import CxrDAELDG
from .cxrdael_wocr import CxrDAELDG_WOCR
from .cxr_crossgrad import CxrCrossGrad
from .cxr_ddaig import CxrDDAIG