INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'normalize']

DATASET:
  NAME: 'CxrDG'
  FINDING_NAMES: ['Atelectasis',
                  'Cardiomegaly',
                  'Consolidation',
                  'Edema',
                  'Effusion',
                  'Pneumonia',
                  'Pneumothorax',
                  'No Finding']
