DATALOADER:
  TRAIN_X:
    SAMPLER: "RandomDomainSampler"
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 128

MODEL:
  BACKBONE:
    NAME: 'resnet18'
    PRETRAINED: True
    
OPTIM:
  NAME: "sgd"
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"

TRAINER:
  DAEL:
    STRONG_TRANSFORMS: ["random_flip", "normalize"]
    
TEST:
  EVALUATOR: 'CxrClassification'