DATALOADER:
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 128

MODEL:
  BACKBONE:
    NAME: 'resnet18'
    PRETRAINED: True

OPTIM:
  NAME: 'sgd'
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: 'cosine'

TRAINER:
  DDAIG:
    G_ARCH: "fcn_3x32_gctx"
    WARMUP: 3
    LMDA: 0.3
    
TEST:
  FINAL_MODEL: "best_val"
  EVALUATOR: 'CxrClassification'


